SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
SCREEN_MARGIN = 100

AMMOUNT_OF_BOIDS = 50

# Algorithm factors
ALIGNMENT_FACTOR = 1.0
COHESION_FACTOR = 0.8
SEPARATION_FACTOR = 1.5

# Eyes
NEIGHBOUR_RANGE = 50
BOID_FOV = 0.2
BOID_SEPARATION_DISTANCE = 15

# Turning settings
BOID_ANGULAR_VELOCITY = 0
BOID_ANGULAR_DUMP = 0.8
BOID_STEER_FORCE = 50

BOID_ACC_RATE = 0.05
BOID_SLOW_RATE = 0.05
BOID_MAX_SPEED = 250
BOID_MIN_SPEED = 100
BOID_MAX_TURN_SPEED = 300
BOID_RADIUS = 10
